
import { myFont, myFontBold } from "@/lib/font";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  author: "MaestroDev007",
  keywords: "Blog, Blog Posts, Next.js, React, Web Development",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable} ${myFontBold.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
